STUB_DIRS <- c(
  "src/cohort_definition",
  "src/clarity_queries",
  "src/validation/cohort_diagnostics",
  "src/validation/chart_review",
  "docs",
  ".advocate"
)

GITIGNORE_CONTENT <- ".advocate/
*.lock
.env
config/local.*
__pycache__/
*.py[cod]
.DS_Store
"

#' Load upstream phenotype data from registry and project YAML
#'
#' @param uuid Character. UUID of the upstream phenotype.
#' @param registry_path Path to registry.yaml. Defaults to the auto-discovered registry.
#' @return Named list with upstream fields.
.load_upstream <- function(uuid, registry_path = NULL) {
  if (is.null(registry_path)) {
    registry_path <- find_registry()
    if (is.null(registry_path)) {
      stop("Registry not found. Set CRIO_LIBRARY_DIR or place registry.yaml in the standard location.")
    }
  }

  if (!file.exists(registry_path)) {
    stop("Registry not found at ", registry_path)
  }

  registry <- yaml::read_yaml(registry_path)
  projects <- registry$projects %||% list()

  entry <- NULL
  for (p in projects) {
    if (identical(as.character(p$id), uuid)) {
      entry <- p
      break
    }
  }

  if (is.null(entry)) {
    stop("UUID ", uuid, " not found in registry. ",
         "Use crio_init() without derive_from to start a new project.")
  }

  project_yaml_path <- file.path(
    dirname(registry_path), "projects", uuid, "advocate-phenotype.yaml"
  )

  if (!file.exists(project_yaml_path)) {
    return(list(
      phenotype_name     = entry$phenotype_name,
      version            = NULL,
      pi_name            = entry$pi_name,
      domain             = entry$domain,
      omop_aligned       = NULL,
      clarity_required   = NULL,
      sce_tier           = entry$sce_tier,
      data_tier          = NULL,
      environment        = NULL,
      inclusion_criteria = NULL,
      exclusion_criteria = NULL,
      ppv                = NULL,
      validation_status  = entry$validation_status
    ))
  }

  schema      <- yaml::read_yaml(project_yaml_path)
  phenotype   <- schema$phenotype   %||% list()
  compute     <- schema$compute     %||% list()
  investigator <- schema$investigator %||% list()

  list(
    phenotype_name     = phenotype$name,
    version            = phenotype$version,
    pi_name            = investigator$pi_name,
    domain             = phenotype$domain,
    omop_aligned       = phenotype$omop_aligned,
    clarity_required   = phenotype$clarity_required,
    sce_tier           = compute$sce_tier,
    data_tier          = compute$data_tier,
    environment        = compute$environment,
    inclusion_criteria = phenotype$inclusion_criteria,
    exclusion_criteria = phenotype$exclusion_criteria,
    ppv                = phenotype$ppv,
    validation_status  = phenotype$validation_status
  )
}

.collect_investigator <- function() {
  cat(cli::style_bold("\n── Investigator ─────────────────────────────────────\n"))
  pi_name  <- .crio_prompt("PI full name")
  pi_email <- .crio_prompt("Institutional email")
  use_orcid <- .crio_confirm("Do you have an ORCID?", default = TRUE)
  pi_orcid <- staff_id <- NULL
  if (use_orcid) {
    pi_orcid <- .crio_prompt("ORCID (0000-0000-0000-0000)")
  } else {
    staff_id <- .crio_prompt("Staff ID")
  }
  list(pi_name = pi_name, pi_email = pi_email,
       pi_orcid = pi_orcid, staff_id = staff_id)
}

.readme_content <- function(name, pi_name, identifier, pi_role,
                             domain, sce_tier, version,
                             validation_status, description,
                             inclusion_criteria, exclusion_criteria) {
  paste0(
    "# ", name, "\n\n",
    "**PI:** ", pi_name, " (", identifier, ")\n",
    "**Role:** ", pi_role, "\n",
    "**Domain:** ", domain, "\n",
    "**SCE Tier:** ", sce_tier, "\n",
    "**Version:** ", version, "\n",
    "**Status:** ", validation_status, "\n\n",
    "## Description\n\n", description, "\n\n",
    "## Inclusion Criteria\n\n", inclusion_criteria, "\n\n",
    "## Exclusion Criteria\n\n", exclusion_criteria, "\n\n",
    "---\n",
    "*Generated by crio. Do not edit directly — ",
    "update advocate-phenotype.yaml and run `crio_publish()`.*\n"
  )
}

#' Initialize a new phenotype project
#'
#' Runs an interactive interview to collect project metadata and writes the
#' advocate-phenotype.yaml schema, README.md, .gitignore, and stub directories.
#'
#' @param output_dir Directory where the project will be created.
#'   Defaults to the current working directory.
#' @param derive_from UUID of an upstream phenotype to derive from.
#' @param registry_path Path to registry.yaml (used when derive_from is set).
#' @return Invisibly returns the path to the project directory.
#' @export
crio_init <- function(output_dir = NULL, derive_from = NULL, registry_path = NULL) {
  upstream <- NULL
  if (!is.null(derive_from)) {
    cat(cli::style_bold("\nLoading upstream phenotype…\n"))
    upstream <- .load_upstream(derive_from, registry_path)
    cat(cli::col_green("✓"), "Found:", cli::style_bold(upstream$phenotype_name %||% derive_from), "\n")
    cat("  PI:", upstream$pi_name %||% "—", "\n")
    cat("  Version:", upstream$version %||% "—", "\n")
    cat("  Status:", upstream$validation_status %||% "—", "\n\n")
  }

  # Investigator section
  inv <- .collect_investigator()

  pi_role <- .crio_choose(
    "PI role",
    c("researcher", "clinical_ops", "data_scientist", "quality_analyst", "informaticist")
  )
  department <- .crio_prompt("Department")

  # Phenotype section
  cat(cli::style_bold("\n── Phenotype ────────────────────────────────────────\n"))
  phenotype_name <- .crio_prompt("Phenotype name")

  domain <- .crio_choose(
    "Domain",
    c("condition", "drug", "procedure", "measurement", "observation")
  )

  description       <- .crio_prompt("Description")
  inclusion_criteria <- .crio_prompt("Inclusion criteria")
  exclusion_criteria <- .crio_prompt("Exclusion criteria")
  omop_aligned      <- .crio_confirm("OMOP aligned?", default = FALSE)
  clarity_required  <- .crio_confirm("Epic Clarity required?", default = FALSE)

  # Compute section
  cat(cli::style_bold("\n── Compute ──────────────────────────────────────────\n"))
  default_tier <- if (!is.null(upstream)) as.character(upstream$sce_tier) else NULL
  sce_tier <- as.integer(.crio_prompt("SCE tier (1-5)", default = default_tier))

  default_dt <- if (!is.null(upstream)) upstream$data_tier else NULL
  data_tier  <- .crio_choose("Data tier", c("A", "B", "C", "D"))
  if (!is.null(upstream$data_tier)) {
    # Honor default from upstream via prompt
    data_tier <- upstream$data_tier
  }

  environment <- .crio_choose(
    "Compute environment",
    c("azure_tre", "gcp", "local")
  )

  # IRB section (required for tier 3+)
  irb_number <- irb_status <- NULL
  if (sce_tier >= 3) {
    cat(cli::style_bold("\n── IRB ──────────────────────────────────────────────\n"))
    irb_number <- .crio_prompt("IRB number")
    irb_status <- .crio_choose("IRB status", c("active", "exempt", "pending"))
  }
  funding_source <- .crio_prompt("Funding source (optional, Enter to skip)", default = "")
  if (nchar(funding_source) == 0) funding_source <- NULL

  # Derivation rationale (if deriving)
  derivation_rationale <- NULL
  derived_version      <- NULL
  if (!is.null(derive_from)) {
    derivation_rationale <- .crio_prompt("Derivation rationale")
    derived_version      <- upstream$version
  }

  project_id <- as.character(uuid::UUIDgenerate())
  now        <- .crio_now()

  project_block <- list(
    id      = project_id,
    created = now,
    updated = now
  )
  if (!is.null(derive_from)) {
    project_block$derived_from         <- derive_from
    project_block$derived_version      <- derived_version
    project_block$derivation_rationale <- derivation_rationale
  }

  # inherited_criteria
  .criteria_status <- function(current, up) {
    if (is.null(up)) return("new")
    if (identical(current, up)) "inherited" else "modified"
  }
  inherited_criteria <- NULL
  if (!is.null(derive_from)) {
    inherited_criteria <- list(
      list(
        field        = "inclusion_criteria",
        from_version = derived_version,
        status       = .criteria_status(inclusion_criteria, upstream$inclusion_criteria)
      ),
      list(
        field        = "exclusion_criteria",
        from_version = derived_version,
        status       = .criteria_status(exclusion_criteria, upstream$exclusion_criteria)
      )
    )
  }

  identifier <- inv$pi_orcid %||% inv$staff_id

  schema <- list(
    project = project_block,
    investigator = list(
      pi_name      = inv$pi_name,
      pi_email     = inv$pi_email,
      pi_role      = pi_role,
      pi_orcid     = inv$pi_orcid,
      staff_id     = inv$staff_id,
      contributors = list()
    ),
    institution = list(
      department     = department,
      irb_number     = irb_number,
      irb_status     = irb_status,
      funding_source = funding_source
    ),
    compute = list(
      sce_tier     = sce_tier,
      data_tier    = data_tier,
      environment  = environment,
      requested_at = now,
      approved_at  = NULL,
      expires_at   = NULL
    ),
    phenotype = list(
      name               = phenotype_name,
      version            = "0.1.0",
      domain             = domain,
      omop_aligned       = omop_aligned,
      clarity_required   = clarity_required,
      target_concept_ids = list(),
      icd_codes          = list(),
      description        = description,
      inclusion_criteria = inclusion_criteria,
      exclusion_criteria = exclusion_criteria,
      validation_status  = "draft",
      validation_method  = "none",
      ppv                = NULL,
      phekb_id           = NULL,
      ohdsi_pl_id        = NULL,
      inherited_criteria = inherited_criteria
    ),
    outputs = list(
      reusable_assets     = list(),
      publications        = list(),
      downstream_projects = list()
    ),
    contribution = list(
      deposit_eligible  = FALSE,
      deposit_submitted = FALSE,
      deposit_date      = NULL,
      credit_granted    = FALSE
    )
  )

  project_dir <- if (!is.null(output_dir)) {
    normalizePath(output_dir, mustWork = FALSE)
  } else {
    getwd()
  }
  dir.create(project_dir, recursive = TRUE, showWarnings = FALSE)

  for (stub in STUB_DIRS) {
    dir.create(file.path(project_dir, stub), recursive = TRUE, showWarnings = FALSE)
  }

  .write_schema(schema, file.path(project_dir, "advocate-phenotype.yaml"))

  writeLines(GITIGNORE_CONTENT, file.path(project_dir, ".gitignore"))

  writeLines(
    .readme_content(
      name               = phenotype_name,
      pi_name            = inv$pi_name,
      identifier         = identifier,
      pi_role            = pi_role,
      domain             = domain,
      sce_tier           = sce_tier,
      version            = "0.1.0",
      validation_status  = "draft",
      description        = description,
      inclusion_criteria = inclusion_criteria,
      exclusion_criteria = exclusion_criteria
    ),
    file.path(project_dir, "README.md")
  )

  cat(cli::col_green("\n✓"), "Project initialized · UUID:", project_id, "\n")
  cat("  Run: crio_source()\n\n")

  invisible(project_dir)
}
